# Generated by Django 3.1.4 on 2021-11-05 05:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_auto_20211027_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='boat',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
