# Generated by Django 3.2.6 on 2022-01-03 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_alter_payment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='animal_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
