# Generated by Django 3.1.4 on 2021-11-07 03:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0003_animal_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('place', models.CharField(max_length=50)),
                ('certificate', models.FileField(blank=True, null=True, upload_to='files')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
