# Generated by Django 3.1.4 on 2021-11-07 04:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0004_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
