# Generated by Django 3.1.4 on 2021-11-07 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0005_animal_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
