# Generated by Django 3.1.4 on 2021-11-07 06:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0006_animal_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='phone',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
