# Generated by Django 3.2.6 on 2022-01-03 11:31

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0011_foodproducts_loan_loantype_symptoms'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
    ]
