# Generated by Django 3.2.6 on 2022-01-08 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0015_auto_20220108_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='symptoms',
            name='amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='symptoms',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='animal.doctor'),
        ),
    ]
