# Generated by Django 3.2.6 on 2022-01-08 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0016_auto_20220108_1813'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='symptoms',
            name='amount',
        ),
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('amount', models.IntegerField()),
                ('symptom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='animal.symptoms')),
            ],
        ),
    ]
