# Generated by Django 3.2.6 on 2022-01-08 14:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0017_auto_20220108_1901'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='birth_date',
        ),
        migrations.AddField(
            model_name='animal',
            name='month',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='animal',
            name='year',
            field=models.IntegerField(default=2021),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctor',
            name='license',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='fertilizer',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='foodproducts',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='animal',
            name='animal_type',
            field=models.CharField(blank=True, choices=[('pet', 'pet'), ('farm', 'farm')], default='pet', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='symptoms',
            name='animal_type',
            field=models.CharField(blank=True, choices=[('pet', 'pet'), ('farm', 'farm')], default='pet', max_length=50, null=True),
        ),
    ]
